### ISSUE TITLE
Handle missing param.sfo better

### ISSUE THREAD

**Issue by maxton** [maxton/LibOrbisPkg#10]
PkgEditor throws an arcane, uncaught exception if you didn't put a param.sfo in sce_sys. Improve this UX.

**Comment by xXxTheDarkprogramerxXx** [comment]
you can always use my sfo editor if you want bud ? it makes sfo's from scratch as well 
https://github.com/xXxTheDarkprogramerxXx/PS3Tools/tree/master/PARAM.SFO%20Editor
