### ISSUE TITLE
question: passcode from package

### ISSUE THREAD

**Issue by tomazzz369** [maxton/LibOrbisPkg#24]
i noticed in Keys.cs: // Used to encrypt Passcode in ENTRY_KEYS

is possible to reverse process, to get passcode from package retail/debug?

regards

**Comment by maxton** [comment]
Nope, that is just the public modulus which is not enough to decrypt (RSA is not symmetric encryption). The private key is probably locked in the PS4's hardware, or only exists at Sony, since there is no need for the console to decrypt the passcode.
