### ISSUE TITLE
Support multi-core process?

### ISSUE THREAD

**Issue by alpakeno** [maxton/LibOrbisPkg#36]
Sony orbis-pub is very faster than LibOrbisPkg, I know it's still work-in-progress project,
But if it's have that it will be a great.
Thanks.

**Comment by maxton** [comment]
LibOrbisPkg has been multi-core since e943a2ea676b9a72ddbfc7c5bece5f47efc71221. Only extraction is single-core but that's not really the focus of the library at the moment.

**Comment by alpakeno** [comment]
Yeah, I mean for the extraction process, it's really slow compared to Sony's tool.
