### ISSUE TITLE
Cannot extract large files in the latest commit.

### ISSUE THREAD

**Issue by alpakeno** [maxton/LibOrbisPkg#37]
"Not enough memory resources are available to process this command."
When trying to extract large file, tried on CUSA-06426 update pkg.
pkg-size is 1.63GB, after extract it became 3.2GB, contain one large file with size of 3.2GB.

**Comment by maxton** [comment]
I can't reproduce this, I was able to extract a 3.5GB PKG to over 6GB with no problems. Do note that update pkgs are not officially supported by this library.

**Comment by alpakeno** [comment]
Thank you for your reply.
Found the culprit that caused it, platform target CPU was on x86 instead of Any and my OS is 64Bit.
Now it throw another error by using var type instead of long when reading pos in large pkg, but when changed to long it works without any problem... don't know if it caused by the compiler or not..
So If it's normal then please close this Issue.

**Comment by gandalfthewhite19890404** [comment]
Large(>60GB) PKGs unpacking with VERY HIGH memory consuming, my RAM -32GB, looks like memory leak.
