### ISSUE TITLE
Can I use this in my GM:S -> ps4 tool?

### ISSUE THREAD

**Issue by KuromeSan** [maxton/LibOrbisPkg#38]
I'd like to use the library :)  maybe modify it a bit to work for my needs .

**Comment by maxton** [comment]
The library is LGPLv3 licensed, so as long as you follow the terms of the license, you're all set to use it.

**Comment by maxton** [comment]
You need to include the license and copyright notice when you distribute the library, so there should at least be a text file included with the zip download with a copyright notice like "This software uses the LibOrbisPkg library. Copyright 2018, 2019 Maxton" and the contents of the LGPL v3.0, which is included with all builds on appveyor

**Comment by KuromeSan** [comment]
Ah, i had the license here : https://bitbucket.org/SilicaAndPina/gaymaker-studio/src/master/LICENSE.md but its not in the .zip i'll be sure to go do that
