### ISSUE TITLE
extractentry - decrypt encrypted entries

### ISSUE THREAD

**Issue by tomazzz369** [maxton/LibOrbisPkg#39]
if possible, decrypt encrypted entries like: license.dat, license.info

regards

**Comment by maxton** [comment]
It's possible to decrypt the license.dat entry, but we're missing the RSA key that decrypts the AES key seed for license.info

Of course, if a passcode is provided then we could just generate the key seeds and decrypt both entries...

**Comment by tomazzz369** [comment]
filelist for PkgTool would be useful, for example in this form:

sce_sys\param.sfo (1 328 bytes)
sce_sys\about\right.suprx (15 520 bytes)
sce_sys\clearsign (512 bytes)
sce_sys\icon0.png (12 952 bytes)
sce_sys\keystone (96 bytes)
...

------------

also currently processed file on extraction, for example:

extracting: sce_sys\icon0.png
extracting: sce_sys\keystone
...

or percentage progress

**Comment by maxton** [comment]
Entry decryption has been implemented in 37da9592c9b29bdc3cbfbbc0ed02a63167d4ac0a
Extraction progress (verbose mode) implemented in 84dbd3182e55c925929179dce6c41fbea55deafa

**Comment by Zer0xFF** [comment]
i'm looking to decrypt license.dat, but its not showing up in the file view, in fact, most of Sc0 entries are missing?

**Comment by maxton** [comment]
Right now you can only extract entries using the command line (PkgTool)

**Comment by maxton** [comment]
Ok, now you can do it from the Entries view in the PkgEditor as well.

**Comment by Zer0xFF** [comment]
great thanks 👍
