### ISSUE TITLE
package supported types

### ISSUE THREAD

**Issue by tomazzz369** [maxton/LibOrbisPkg#41]
small question, because there is no any info. what types of packages are supported for makepkg, i'm asking because i tried to make theme package, but tool build package as DLC, not theme (<volume_type>pkg_ps4_theme</volume_type>). regards

**Comment by tomazzz369** [comment]
sorry, i'm not sure why but can't edit previous post

seems too IROTag is not set to 0x2 if package type is theme

**Comment by maxton** [comment]
Only pkg_ps4_app and pkg_ps4_ac_data are currently fully supported. If you know the changes required to make a theme (beyond the IROTag) I can add support.
