### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by smasher248** [maxton/LibOrbisPkg#46]
I Get this error when opening a PKG built by command line, it also error when installing on PS4
![image](https://user-images.githubusercontent.com/57395247/68200537-04bbe980-ffb8-11e9-8315-ab3eb265da35.png)

**Comment by smasher248** [comment]
> I Get this error when opening a PKG built by command line, it also error when installing on PS4
> ![image](https://user-images.githubusercontent.com/57395247/68200537-04bbe980-ffb8-11e9-8315-ab3eb265da35.png)

Nvm, just found a different program that works

**Comment by maxton** [comment]
Can you upload this PKG somewhere so I can see what the issue is? What command did you use to build it?

**Comment by smasher248** [comment]
No longer have this program or the PKG unfortunately, I'm using Orbis fake PKG, sorry
