### ISSUE TITLE
PkgBuilder

### ISSUE THREAD

**Issue by bocaderf** [maxton/LibOrbisPkg#53]
Hi,
in CalcPlaygoDigests can you check if a cast for chunk * CHUNK_SIZE to (long) must be done to prevent negative value if the int > maxint value for the view.ReadArray position parameter.
For example 
              long c = chunk;
              c *= CHUNK_SIZE;
              view.ReadArray(c, buffer, 0, CHUNK_SIZE);

(to make it clear ;-)
Thx
Fred.

**Comment by maxton** [comment]
Good catch. I never tested building game PKGs larger than 2GB
