### ISSUE TITLE
Error CS0006 LibOrbisPkg.dll' could not be found

### ISSUE THREAD

**Issue by ashhh123** [maxton/LibOrbisPkg#57]
Hi i have errors when i tried to running the system. Metadata file 'C:\***\***\Desktop\LibOrbisPkg-master\LibOrbisPkg\bin\Debug\LibOrbisPkg.dll' could not be found

**Comment by maxton** [comment]
Use one of the builds from here: https://ci.appveyor.com/project/maxton/liborbispkg/build/artifacts
