### ISSUE TITLE
PKG Editor XML and GP4 error

### ISSUE THREAD

**Issue by TheBatmanWhoLaughs13** [maxton/LibOrbisPkg#61]
Can you look into this as it won't read GP4 files when I try to open one and when I try to create one and build PKG it kicks back an XML error

**Comment by maxton** [comment]
Please attach a sample GP4 file that isn't working so I can reproduce this error

**Comment by NikolausC** [comment]
If the XML version specified in the GP4 file is 1.1, it’ll crash when attempting to open. Changing it to 1.0 works.

**Comment by TheBatmanWhoLaughs13** [comment]
Yeah, mine shows 1.1 how do you change it to 1.0?

**Comment by NikolausC** [comment]
Open it in a text editor

**Comment by TheBatmanWhoLaughs13** [comment]
That fixed the problem. Thanks.

By the day does it normally take 5 plus hours to make a PKG from this tool? Doing a 98 gig PKG...unless it's based on the size...
