### ISSUE TITLE
PkgEditor dont extract gp4 project correctly for fPKG of a update and dont repack it correctly too.

### ISSUE THREAD

**Issue by fabrebatalla18** [maxton/LibOrbisPkg#62]
PkgEditor dont extract gp4 project correctly for fPKG of a update and dont repack it correctly too.

Thats it, PkgEditor dont support the <volume_type>pkg_ps4_patch</volume_type> (unpack or repack).

**Comment by maxton** [comment]
I have no plans to add support for patch PKGs because they won't be used for homebrew. If you want to implement it I will review your PRs
