### ISSUE TITLE
SCE_KERNEL_ERROR_ENOENT

### ISSUE THREAD

**Issue by TheBatmanWhoLaughs13** [maxton/LibOrbisPkg#66]
I spent 5 plus hours trying to build a PKG..it finished but when I got it install it in my system it goes into SCE_KERNEL_ERROR_ENOENT ce-30002-5

Not sure if your program caused it as all my other ones install fine built with other tools.

Wanted to give these a shot

**Comment by maxton** [comment]
Is this a homebrew game?

**Comment by TheBatmanWhoLaughs13** [comment]
No, it was fpkg for God of war. 

I haven't tried using the app since. I may try it again with a smaller app to see what happens

**Comment by maxton** [comment]
Pirated games aren't supported. They use playgo, but homebrew doesn't.
