### ISSUE TITLE
PkgTool Generates Invalid FPKG

### ISSUE THREAD

**Issue by 78Alpha** [maxton/LibOrbisPkg#68]
I have been trying to find a good command line FPKG builder, and this appeared to be the only one. I have been testing it compared to the more dedicated tools (The GUI interface tools) but every FPKG generated causes an error on the PS4 system. FPKGs built with the GUI tools work just fine though.

Files generated throw errors that certain files should not exist or that their SLEF is invalid. Removing offending files without altering SELF did not fix the issue.

**Comment by hippie68** [comment]
Did you find a solution? I have the same trouble, and am currently under the impression that PkgTool is not made to turn dumps into PKGs. It seems to work for turning existing PKGs into files (that are different from a dump as some files are missing then and some are altered) and back again though. Of course, I might be wrong. If I'm right, I think this should be made clear in the Readme, so it saves people looking to turn dumps into PKGs a lot of time.

**Comment by 78Alpha** [comment]
@hippie68 I have not found one with this tool. Looked at the source, and even though C# is alien to me, couldn't find any overly out of place pieces (more like parts that seem... missing? Or obfuscated).

I use this tool for image extraction in bulk but use orbis-pub-gen for image creation. It works for everything but DLC.

**Comment by maxton** [comment]
This tool is for building homebrew FPKGs, it doesn't do anything with SELFs. Make sure you follow the instructions at e.g. https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain to generate a proper eboot.bin
